### PR TITLE
Enhancement: Code cleanup and creation of mocks

### LINKED ISSUE #13: Creation of Data Transfer Objects
In order to represent an entity to the user, like courses, classes, etc... we need to create Data Transfer Objects (aka DTO) in our project.
This can be created from collecting information from any resource provider and filtering any desirable information to be shown.

The following DTOs needs to be done:
 - CourseDto
 - ClassSectionDto
 - CurricularTermsDto

### LINKED ISSUE #14: Mock of the i-on read API
The mock should have the same interface as the real api class. 
Everything should the same as the real api with the exception of the data source,
this includes parsing.

One should: 
 - Create the interface 
 - Implement a mock from the interface

### LINKED ISSUE #15: Creation of ViewModels and ViewModel providers
For each fragment a ViewModel and a ViewModelProvider should be created. 

A SharedViewModel should also be created to share information between fragments.

### LINKED ISSUE #19: Enhancement: Code cleanup and create more mocks
The project needs to have a code cleanup and it needs to have more mocks for every course, their classes and their respective class sections, atleast for the 1st curricular term.
With this mocks, we can implement and test the class section selection using local database to store the user choices.

We can also improve certain features, layout of the fragments and/or how can we retrieve information from the mocks and parse them to SirenEntities...

### PR DESCRIPTION
**Pull request by JoniBife**
In this branch we cleaned our project code, created all mocks for every 1st curricular term's courses and their respective classes/class sections and improved some of our "code logic" and changed the fragment's layouts.

Next step should be implementation of the class section's selection using room database to store the favorite class sections choosen by the user.

Close #19
Closes #15 
Closes #14 
Closes #13

### CODE REVIEW

File: Project/app/src/main/java/org/ionproject/android/SharedViewModel.kt [hunk 1]
```diff
@@ -0,0 +1,21 @@
+package org.ionproject.android
+
+import androidx.lifecycle.LifecycleOwner
```
Comment (palbp) [inline Project/app/src/main/java/org/ionproject/android/SharedViewModel.kt:3]: Some unused imports still linger here

File: Project/app/src/main/java/org/ionproject/android/SharedViewModel.kt [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+import androidx.lifecycle.MutableLiveData
+import androidx.lifecycle.Observer
+import androidx.lifecycle.ViewModel
+import org.ionproject.android.common.model.ClassSummary
+import org.ionproject.android.common.model.CourseSummary
+
+class SharedViewModel : ViewModel() {
+
+    // Search text used to pass data from search bar to searchResultFragment
```
Comment (palbp) [inline Project/app/src/main/java/org/ionproject/android/SharedViewModel.kt:12]: BTW, this is not KDoc, but it should be. I also have doubts regarding the use of lateinit here. Shouldn't it be nullable instead?

File: Project/app/src/main/java/org/ionproject/android/SharedViewModel.kt [hunk 3]
```diff
@@ -0,0 +1,21 @@
+package org.ionproject.android
+
+import androidx.lifecycle.LifecycleOwner
+import androidx.lifecycle.MutableLiveData
+import androidx.lifecycle.Observer
+import androidx.lifecycle.ViewModel
+import org.ionproject.android.common.model.ClassSummary
+import org.ionproject.android.common.model.CourseSummary
+
```
Comment (palbp) [inline Project/app/src/main/java/org/ionproject/android/SharedViewModel.kt:9]: This class materializes a contract, right? It deserves to be documented. Please do not forget to document appropriately all contracts that are defined within the application (with KDoc).

File: Project/app/src/main/java/org/ionproject/android/class_section/ClassSectionFragment.kt [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+import android.view.View
+import android.view.ViewGroup
+import androidx.fragment.app.Fragment
+import androidx.fragment.app.activityViewModels
+import androidx.lifecycle.ViewModelProviders
+import kotlinx.android.synthetic.main.fragment_class_section.*
+import org.ionproject.android.class_section.ClassSectionViewModel
+import org.ionproject.android.class_section.ClassSectionViewModelProvider
+
+/**
```
Comment (palbp) [inline Project/app/src/main/java/org/ionproject/android/class_section/ClassSectionFragment.kt:14]: This is temporary, right? It does not document anything. If there isn´t much to say, then we should focus on our domain: for example, the class implements a fragment used to display a class section. If it's only used in some contexts, then state it too.

**Review by palbp — APPROVED** [review]

File: Project/app/src/main/java/org/ionproject/android/class_section/ClassSectionFragment.kt (hunk 4 above)
Comment (JoniBife) [reply Project/app/src/main/java/org/ionproject/android/class_section/ClassSectionFragment.kt:14]: Yes, it's temporary

File: Project/app/src/main/java/org/ionproject/android/SharedViewModel.kt (hunk 2 above)
Comment (JoniBife) [reply Project/app/src/main/java/org/ionproject/android/SharedViewModel.kt:12]: With the way the navigation has been setup within the app, I don't think it's possible to ever not have a value in one of those fields, but, making them nullable would improve legibility for sure, I hadn't thought about that.

File: Project/app/src/main/java/org/ionproject/android/common/ionwebapi/JacksonIonMapper.kt [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+            if (res.isFailure) {
+                Log.println(
+                    Log.DEBUG,
+                    "COURSES",
+                    "Failed parsing to SirenEntity, exception : ${res.exceptionOrNull()}"
+                )
+                throw res.exceptionOrNull()!! //This will never return null here
+            }
+            Log.println(Log.DEBUG, "COURSES", "Successfully parsed to SirenEntity")
+            res.getOrNull()!!
```
Comment (palbp) [inline Project/app/src/main/java/org/ionproject/android/common/ionwebapi/JacksonIonMapper.kt]: There it is, the infamous !!
As I've said before, it usually reveals poor use of the constructs.
Presuming that you really have to log here (I doubt of its usefulness), we could write it using:
`val entity = kotlin.runCatching {
                    jacksonObjMapper.readValue<SirenEntity>(responseBody)
                }.getOrThrow()`

I didn't place here the full reimplementation because it was not properly formatted =-/

File: Project/app/src/main/java/org/ionproject/android/class_section/ClassSectionDto.kt [hunk 6]
```diff
@@ -0,0 +1,27 @@
...
+ */
+fun SirenEntity.toClassSection(): ClassSection {
+    val calendarURI: URI? = (entities?.first() as EmbeddedEntity).links?.first()?.href
+
+    if (properties != null && properties["course"] != null && properties["class"] != null
+        && properties["id"] != null
+    ) {
+        //Using double bang operator because we are sure this properties cannot be null here
+        return ClassSection(
+            course = properties["course"]!!,
```
Comment (palbp) [inline Project/app/src/main/java/org/ionproject/android/class_section/ClassSectionDto.kt:20]: Again... Please do not use !!
Use properties.getOrDefault() or something else. If your intention is to force an exception to be thrown, then create the appropriate exception and throw it.
BTW, you state that "we are sure that it cannot be null". Are you really?

Comment (JoniBife) [reply Project/app/src/main/java/org/ionproject/android/class_section/ClassSectionDto.kt:20]: This has been changed in ClassesSelection branch. https://github.com/i-on-project/android/pull/25#

File: Project/app/src/main/java/org/ionproject/android/common/ionwebapi/JacksonIonMapper.kt (hunk 5 above)
Comment (JoniBife) [reply Project/app/src/main/java/org/ionproject/android/common/ionwebapi/JacksonIonMapper.kt]: Actually this log is was extremely useful while we were developing, but that implementation is better. Will do the change before merge.
